version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "90:90"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_management
    ports:
      - "5432:5432"
